import { Mulish } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";

import "./globals.css";

// Font
const mulish = Mulish({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-mulish",
});

// Components
import Drawer from "./components/Drawer";

// MetaData
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.variable}>
        <Drawer>{children}</Drawer>
      </body>
    </html>
  );
}
